## 라이브러리 불러오기
- numpy 라이브러리를 불러온다.

In [1]:
import numpy as np 
print(np.__version__)

1.21.6

# 배열 생성의 다양한 방법들

- 모두 0으로 채운다.

In [2]:
temp_arr = np.zeros((2, 3))
temp_arr

array([[0., 0., 0.],
       [0., 0., 0.]])

- 모두 1로 채운다.

In [3]:
temp_arr = np.ones((2, 3))
temp_arr

array([[1., 1., 1.],
       [1., 1., 1.]])

- 임의의 상수값으로 채운다.

In [4]:
temp_arr = np.full((2, 3), 100)
temp_arr

array([[100, 100, 100],
       [100, 100, 100]])

- 이번에는 최소 및 최대 숫자의 범위를 정해두고 구간별로 값을 생성하는 코드를 작성한다.

In [5]:
temp_arr = np.linspace(5, 10, 5)
temp_arr

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])

- 반복문 시, 자주 사용하는 배열을 작성한다.

In [6]:
temp_arr = np.arange(1, 11, 1)
temp_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

- 이번에는 임의의 난수 생성을 확인한다.

In [7]:
# import numpy as np
from numpy import random 
# y = np.random.rand()
# print(y)
x = random.rand()
print(x)

0.9173912877800918
0.7938971758724641

- 랜덤 배열을 생성한다. (Integer)

In [8]:
from numpy import random
x = random.randint(100, size = (5)) 
print(x)
type(x)

[74 75 92 73 86]

numpy.ndarray

In [ ]:
x = random.randint(100, size = (2, 5)) 
print(x)
type(x)

[[30 60 50 50 23]
 [89 47 96 79 65]]

numpy.ndarray

- 랜덤 배열을 생성한다. (Floats)

In [ ]:
from numpy import random
x = random.rand(2, 5)
print(x)

[[0.82723869 0.14364097 0.41556165 0.29365039 0.80244706]
 [0.67223561 0.90723893 0.43280079 0.3740873  0.40791857]]

# 배열 연산
- 간단한 사칙 연산을 구현한다.

In [9]:
import numpy as np
array_01 = np.array([1, 2, 3])
array_02 = np.array([10, 20, 30])

In [10]:
# 덧셈
newArr = np.add(array_01, array_02)
print("덧셈: ", newArr)

덧셈:  [11 22 33]

In [11]:
# 뺄셈
newArr = np.subtract(array_01, array_02)
print("뺄셈: ", newArr)

뺄셈:  [ -9 -18 -27]

In [12]:
# 곱셈
newArr = np.multiply(array_01, array_02)
print("곱셈: ", newArr)

곱셈:  [10 40 90]

In [13]:
# 나눗셈
newArr = np.divide(array_01, array_02)
print("나눗셈: ", newArr)

나눗셈:  [0.1 0.1 0.1]

In [14]:
# 거듭제곱
array_01 = np.array([1, 2, 3])
array_02 = np.array([1, 2, 3])

newArr = np.power(array_01, array_02)
print("거듭제곱: ", newArr)

거듭제곱:  [ 1  4 27]

# 소숫점 정렬

- 소숫점을 제거하는 코드를 작성한다.

In [15]:
import numpy as np 
temp_arr = np.trunc([-1.23, 1.23])
print(temp_arr)

[-1.  1.]

In [16]:
temp_arr = np.fix([-1.23, 1.23])
print(temp_arr)

[-1.  1.]

- 임의의 소숫점 자리에서 반올림

In [17]:
temp_arr = np.around([-1.23723451, 1.2312315], 3)
print(temp_arr)

[-1.237  1.231]

In [18]:
temp_arr = np.round([-1.23723451, 1.2312315], 3)
print(temp_arr)

[-1.237  1.231]

- 소수점 모두 내린다.

In [19]:
temp_arr = np.floor([-1.23723451, 1.2312315])
print(temp_arr)

[-2.  1.]

- 소수점 모두 올린다.

In [20]:
temp_arr = np.ceil([-1.23723451, 1.2312315])
print(temp_arr)

[-1.  2.]

# numpy.where
- 조건식

In [ ]:
temp_arr = np.arange(10)
temp_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
import numpy as np 
temp_arr = np.arange(10)
np.where(temp_arr < 5, temp_arr, 10*temp_arr)

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

# numpy.select
- 조건식 list

In [ ]:
temp_arr = np.arange(10)
temp_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
temp_arr = np.arange(10)
cond_list = [temp_arr > 5, temp_arr < 2]

choice_list = [temp_arr * 2, temp_arr + 100]
np.select(cond_list,choice_list, default = temp_arr)

array([100, 101,   2,   3,   4,   5,  12,  14,  16,  18])

# NumPy와 Pandas와의 조합
- 어떤 과일 가게의 데이터셋을 임의로 생성했다.
- https://medium.com/analytics-vidhya/demystifying-np-where-and-np-select-76e3ca49e316

In [ ]:
import pandas as pd 
import numpy as np

df = pd.DataFrame({
    '과일': ['사과', '자두', '사과', '자두'],
    '판매사': ['A', 'A', 'B', 'B'],
    '판매무게 (kg)': [10,20,30,40],
    '판매별점': [4, 3, 5, 3.5]
})

In [ ]:
A_price = pd.DataFrame({
    '과일': ['사과', '바나나', '자두', '파인애플'],
    '가격 (kg)': [7000, 5000, 5000, 6000]
})

B_price = pd.DataFrame({
    '과일': ['사과', '바나나', '자두', '파인애플'],
    '가격 (kg)': [6500, 5500, 6000, 5000]
})

- 기존 df에 각 품목에 맞는 것만 가져와서 kg당 가격을 추가하는 코드를 짜본다. 
- 먼저 `fruit` 함수를 인덱스로 추가한다.

In [ ]:
df = df.set_index("과일")
A_price = A_price.set_index("과일")
B_price = B_price.set_index("과일")

- np.where 함수를 적용하여 각 판매사에 맞는 kg당 가격을 추가한다.

In [ ]:
df['가격 (kg)'] = np.where(
    df['판매사'] == 'A', 
    A_price.loc[df.index]['가격 (kg)'], 
    B_price.loc[df.index]['가격 (kg)']
)

df

   판매사  판매무게 (kg)  판매별점  가격 (kg)
과일
사과   A         10   4.0     7000
자두   A         20   3.0     5000
사과   B         30   5.0     6500
자두   B         40   3.5     6000

- 이번에는 판매사가 3개일 때 경우의 수를 생각해본다.

In [ ]:
import pandas as pd 
import numpy as np

df = pd.DataFrame({
    '과일': ['사과', '자두', '사과', '자두', '사과', '자두'],
    '판매사': ['A', 'A', 'B', 'B', 'C', 'C'],
    '판매무게 (kg)': [10,20,30,40, 15, 20],
    '판매별점': [4, 3, 5, 3.5, 4, 5]
})

df_price = pd.DataFrame({
    '과일': ['사과', '바나나', '자두', '파인애플'],
    'A' : [7000, 5000, 5000, 6000], 
    'B' : [6500, 5500, 6000, 5000], 
    'C' : [2000, 3000, 3000, 4000]
})

In [ ]:
df = df.set_index("과일")
df

   판매사  판매무게 (kg)  판매별점
과일
사과   A         10   4.0
자두   A         20   3.0
사과   B         30   5.0
자두   B         40   3.5
사과   C         15   4.0
자두   C         20   5.0

In [ ]:
df_price = df_price.set_index('과일')
df_price

         A     B     C
과일
사과    7000  6500  2000
바나나   5000  5500  3000
자두    5000  6000  3000
파인애플  6000  5000  4000

In [ ]:
args = df_price.loc[df.index]
args

       A     B     C
과일
사과  7000  6500  2000
자두  5000  6000  3000
사과  7000  6500  2000
자두  5000  6000  3000
사과  7000  6500  2000
자두  5000  6000  3000

In [ ]:
conds = [
    df['판매사'] == 'A', 
    df['판매사'] == 'B', 
    df['판매사'] == 'C', 
]

choices = [
    args['A'], 
    args['B'], 
    args['C']
]
choices

[과일
 사과    7000
 자두    5000
 사과    7000
 자두    5000
 사과    7000
 자두    5000
 Name: A, dtype: int64, 과일
 사과    6500
 자두    6000
 사과    6500
 자두    6000
 사과    6500
 자두    6000
 Name: B, dtype: int64, 과일
 사과    2000
 자두    3000
 사과    2000
 자두    3000
 사과    2000
 자두    3000
 Name: C, dtype: int64]

In [ ]:
df['price (kg)'] = np.select(conds, choices)
df

   판매사  판매무게 (kg)  판매별점  price (kg)
과일
사과   A         10   4.0        7000
자두   A         20   3.0        5000
사과   B         30   5.0        6500
자두   B         40   3.5        6000
사과   C         15   4.0        2000
자두   C         20   5.0        3000