# JSON

- 참고싸이트: http://data.ex.co.kr/dataset/datasetList/list?pn=1&CATEGORY=TR&GROUP_TR=TIME_TCS

In [1]:
import requests

url = "http://data.ex.co.kr/openapi/trtm/realUnitTrtm?key=1308370912&type=json&iStartUnitCode=101&iEndUnitCode=103"

In [2]:
responses = requests.get(url)
print(responses)

<Response [200]>

In [3]:
json = responses.json()
json

{'code': 'SUCCESS',
 'count': 1187,
 'message': '인증키가 유효합니다.',
 'numOfRows': 10,
 'pageNo': 1,
 'pageSize': 119,
 'realUnitTrtmVO': [{'efcvTrfl': '17',
   'endUnitCode': '103 ',
   'endUnitNm': '수원신갈',
   'iEndUnitCode': None,
   'iStartEndStdTypeCode': None,
   'iStartUnitCode': None,
   'numOfRows': None,
   'pageNo': None,
   'startEndStdTypeCode': '2',
   'startEndStdTypeNm': '도착기준통행시간',
   'startUnitCode': '101 ',
   'startUnitNm': '서울',
   'stdDate': '20220306',
   'stdTime': '00:25',
   'sumTmUnitTypeCode': None,
   'tcsCarTypeCode': '1',
   'tcsCarTypeDivCode': '1',
   'tcsCarTypeDivName': '소형차',
   'tcsCarTypeName': '1종',
   'timeAvg': '7.533333333333333',
   'timeMax': '9.066',
   'timeMin': '5.850'},
  {'efcvTrfl': '57',
   'endUnitCode': '103 ',
   'endUnitNm': '수원신갈',
   'iEndUnitCode': None,
   'iStartEndStdTypeCode': None,
   'iStartUnitCode': None,
   'numOfRows': None,
   'pageNo': None,
   'startEndStdTypeCode': '2',
   'startEndStdTypeNm': '도착기준통행시간',
   'startUnitCode': '101 ',
   'startUnitNm': '서울',
   'stdDate': '20220306',
   'stdTime': '00:30',
   'sumTmUnitTypeCode': None,
   'tcsCarTypeCode': '1',
   'tcsCarTypeDivCode': '1',
   'tcsCarTypeDivName': '소형차',
   'tcsCarTypeName': '1종',
   'timeAvg': '7.475',
   'timeMax': '10.566',
   'timeMin': '5.750'},
  {'efcvTrfl': '16',
   'endUnitCode': '103 ',
   'endUnitNm': '수원신갈',
   'iEndUnitCode': None,
   'iStartEndStdTypeCode': None,
   'iStartUnitCode': None,
   'numOfRows': None,
   'pageNo': None,
   'startEndStdTypeCode': '2',
   'startEndStdTypeNm': '도착기준통행시간',
   'startUnitCode': '101 ',
   'startUnitNm': '서울',
   'stdDate': '20220306',
   'stdTime': '00:35',
   'sumTmUnitTypeCode': None,
   'tcsCarTypeCode': '1',
   'tcsCarTypeDivCode': '1',
   'tcsCarTypeDivName': '소형차',
   'tcsCarTypeName': '1종',
   'timeAvg': '7.466666666666667',
   'timeMax': '10.566',
   'timeMin': '5.916'},
  {'efcvTrfl': '15',
   'endUnitCode': '103 ',
   'endUnitNm': '수원신갈',
   'iEndUnitCode': None,
   'iStartEndStdTypeCode': None,
   'iStartUnitCode': None,
   'numOfRows': None,
   'pageNo': None,
   'startEndStdTypeCode': '2',
   'startEndStdTypeNm': '도착기준통행시간',
   'startUnitCode': '101 ',
   'startUnitNm': '서울',
   'stdDate': '20220306',
   'stdTime': '00:40',
   'sumTmUnitTypeCode': None,
   'tcsCarTypeCode': '1',
   'tcsCarTypeDivCode': '1',
   'tcsCarTypeDivName': '소형차',
   'tcsCarTypeName': '1종',
   'timeAvg': '7.5',
   'timeMax': '10.133',
   'timeMin': '5.966'},
  {'efcvTrfl': '67',
   'endUnitCode': '103 ',
   'endUnitNm': '수원신갈',
   'iEndUnitCode': None,
   'iStartEndStdTypeCode': None,
   'iStartUnitCode': None,
   'numOfRows': None,
   'pageNo': None,
   'startEndStdTypeCode': '2',
   'startEndStdTypeNm': '도착기준통행시간',
   'startUnitCode': '101 ',
   'startUnitNm': '서울',
   'stdDate': '20220306',
   'stdTime': '00:45',
   'sumTmUnitTypeCode': None,
   'tcsCarTypeCode': '1',
   'tcsCarTypeDivCode': '1',
   'tcsCarTypeDivName': '소형차',
   'tcsCarTypeName': '1종',
   'timeAvg': '7.566666666666666',
   'timeMax': '9.750',
   'timeMin': '5.783'},
  {'efcvTrfl': '14',
   'endUnitCode': '103 ',
   'endUnitNm': '수원신갈',
   'iEndUnitCode': None,
   'iStartEndStdTypeCode': None,
   'iStartUnitCode': None,
   'numOfRows': None,
   'pageNo': None,
   'startEndStdTypeCode': '2',
   'startEndStdTypeNm': '도착기준통행시간',
   'startUnitCode': '101 ',
   'startUnitNm': '서울',
   'stdDate': '20220306',
   'stdTime': '00:50',
   'sumTmUnitTypeCode': None,
   'tcsCarTypeCode': '1',
   'tcsCarTypeDivCode': '1',
   'tcsCarTypeDivName': '소형차',
   'tcsCarTypeName': '1종',
   'timeAvg': '7.483333333333333',
   'timeMax': '8.000',
   'timeMin': '5.966'},
  {'efcvTrfl': '11',
   'endUnitCode': '103 ',
   'endUnitNm': '수원신갈',
   'iEndUnitCode': None,
   'iStartEndStdTypeCode': None,
   'iStartUnitCode': None,
   'numOfRows': None,
   'pageNo': None,
   'startEndStdTypeCode': '2',
   'startEndStdTypeNm': '도착기준통행시간',
   'startUnitCode': '101 ',
   'startUnitNm': '서울',
   'stdDate': '20220306',
   'stdTime': '00:55',
   'sumTmUnitTypeCode': None,
   'tcsCarTypeCode': '1',
   'tcsCarTypeDivCode': '1',
   'tcsCarTypeDivName': '소형차',
   'tcsCarTypeName': '1종',
   'timeAvg': '7.383333333333334',
   'timeMax': '8.500',
   'timeMin': '6.083'},
  {'efcvTrfl': '99',
   'endUnitCode': '103 ',
   'endUnitNm': '수원신갈',
   'iEndUnitCode': None,
   'iStartEndStdTypeCode': None,
   'iStartUnitCode': None,
   'numOfRows': None,
   'pageNo': None,
   'startEndStdTypeCode': '2',
   'startEndStdTypeNm': '도착기준통행시간',
   'startUnitCode': '101 ',
   'startUnitNm': '서울',
   'stdDate': '20220306',
   'stdTime': '01  ',
   'sumTmUnitTypeCode': None,
   'tcsCarTypeCode': '1',
   'tcsCarTypeDivCode': '1',
   'tcsCarTypeDivName': '소형차',
   'tcsCarTypeName': '1종',
   'timeAvg': '7.466666666666667',
   'timeMax': '10.166',
   'timeMin': '5.800'},
  {'efcvTrfl': '35',
   'endUnitCode': '103 ',
   'endUnitNm': '수원신갈',
   'iEndUnitCode': None,
   'iStartEndStdTypeCode': None,
   'iStartUnitCode': None,
   'numOfRows': None,
   'pageNo': None,
   'startEndStdTypeCode': '2',
   'startEndStdTypeNm': '도착기준통행시간',
   'startUnitCode': '101 ',
   'startUnitNm': '서울',
   'stdDate': '20220306',
   'stdTime': '01:00',
   'sumTmUnitTypeCode': None,
   'tcsCarTypeCode': '1',
   'tcsCarTypeDivCode': '1',
   'tcsCarTypeDivName': '소형차',
   'tcsCarTypeName': '1종',
   'timeAvg': '7.416666666666667',
   'timeMax': '9.666',
   'timeMin': '6.183'},
  {'efcvTrfl': '8',
   'endUnitCode': '103 ',
   'endUnitNm': '수원신갈',
   'iEndUnitCode': None,
   'iStartEndStdTypeCode': None,
   'iStartUnitCode': None,
   'numOfRows': None,
   'pageNo': None,
   'startEndStdTypeCode': '2',
   'startEndStdTypeNm': '도착기준통행시간',
   'startUnitCode': '101 ',
   'startUnitNm': '서울',
   'stdDate': '20220306',
   'stdTime': '01:05',
   'sumTmUnitTypeCode': None,
   'tcsCarTypeCode': '1',
   'tcsCarTypeDivCode': '1',
   'tcsCarTypeDivName': '소형차',
   'tcsCarTypeName': '1종',
   'timeAvg': '7.4',
   'timeMax': '8.250',
   'timeMin': '6.833'}]}

In [4]:
cars = json["realUnitTrtmVO"]

In [5]:
records = []
for car in cars:
  dic = {}
  dic["date"] = car["stdDate"]
  dic["time"] = car["stdTime"]
  dic["timeAvg"] = car["timeAvg"]
  records.append(dic)

records

[{'date': '20220306', 'time': '00:25', 'timeAvg': '7.533333333333333'},
 {'date': '20220306', 'time': '00:30', 'timeAvg': '7.475'},
 {'date': '20220306', 'time': '00:35', 'timeAvg': '7.466666666666667'},
 {'date': '20220306', 'time': '00:40', 'timeAvg': '7.5'},
 {'date': '20220306', 'time': '00:45', 'timeAvg': '7.566666666666666'},
 {'date': '20220306', 'time': '00:50', 'timeAvg': '7.483333333333333'},
 {'date': '20220306', 'time': '00:55', 'timeAvg': '7.383333333333334'},
 {'date': '20220306', 'time': '01  ', 'timeAvg': '7.466666666666667'},
 {'date': '20220306', 'time': '01:00', 'timeAvg': '7.416666666666667'},
 {'date': '20220306', 'time': '01:05', 'timeAvg': '7.4'}]

In [6]:
import pandas as pd
df = pd.DataFrame(records)
df["student"] = "홍길동"
df

       date   time            timeAvg student
0  20220306  00:25  7.533333333333333     홍길동
1  20220306  00:30              7.475     홍길동
2  20220306  00:35  7.466666666666667     홍길동
3  20220306  00:40                7.5     홍길동
4  20220306  00:45  7.566666666666666     홍길동
5  20220306  00:50  7.483333333333333     홍길동
6  20220306  00:55  7.383333333333334     홍길동
7  20220306   01    7.466666666666667     홍길동
8  20220306  01:00  7.416666666666667     홍길동
9  20220306  01:05                7.4     홍길동

# XML

In [7]:
import lxml
import requests
from bs4 import BeautifulSoup

url = "http://data.ex.co.kr/openapi/trtm/realUnitTrtm?key=1308370912&type=xml&iStartUnitCode=101&iEndUnitCode=103"
result = requests.get(url)
content = result.content
soup = BeautifulSoup(content, "lxml") # html.parser 
# print(soup)
print(soup.prettify())

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<html>
 <body>
  <data>
   <code>
    SUCCESS
   </code>
   <message>
    인증키가 유효합니다.
   </message>
   <count>
    1187
   </count>
   <numofrows>
    10
   </numofrows>
   <pageno>
    1
   </pageno>
   <pagesize>
    119
   </pagesize>
   <realunittrtmvo>
    <efcvtrfl>
     209
    </efcvtrfl>
    <endunitcode>
     103
    </endunitcode>
    <endunitnm>
     수원신갈
    </endunitnm>
    <startendstdtypecode>
     2
    </startendstdtypecode>
    <startendstdtypenm>
     도착기준통행시간
    </startendstdtypenm>
    <startunitcode>
     101
    </startunitcode>
    <startunitnm>
     서울
    </startunitnm>
    <stddate>
     20220306
    </stddate>
    <stdtime>
     00
    </stdtime>
    <tcscartypecode>
     1
    </tcscartypecode>
    <tcscartypedivcode>
     1
    </tcscartypedivcode>
    <tcscartypedivname>
     소형차
    </tcscartypedivname>
    <tcscartypename>
     1종
    </tcscartypename>
    <timeavg>
     7.516666666666667
    </timeavg>
    <timemax>
     11.350
    </timemax>
    <timemin>
     5.750
    </timemin>
   </realunittrtmvo>
   <realunittrtmvo>
    <efcvtrfl>
     78
    </efcvtrfl>
    <endunitcode>
     103
    </endunitcode>
    <endunitnm>
     수원신갈
    </endunitnm>
    <startendstdtypecode>
     2
    </startendstdtypecode>
    <startendstdtypenm>
     도착기준통행시간
    </startendstdtypenm>
    <startunitcode>
     101
    </startunitcode>
    <startunitnm>
     서울
    </startunitnm>
    <stddate>
     20220306
    </stddate>
    <stdtime>
     00:00
    </stdtime>
    <tcscartypecode>
     1
    </tcscartypecode>
    <tcscartypedivcode>
     1
    </tcscartypedivcode>
    <tcscartypedivname>
     소형차
    </tcscartypedivname>
    <tcscartypename>
     1종
    </tcscartypename>
    <timeavg>
     7.5
    </timeavg>
    <timemax>
     11.350
    </timemax>
    <timemin>
     5.833
    </timemin>
   </realunittrtmvo>
   <realunittrtmvo>
    <efcvtrfl>
     14
    </efcvtrfl>
    <endunitcode>
     103
    </endunitcode>
    <endunitnm>
     수원신갈
    </endunitnm>
    <startendstdtypecode>
     2
    </startendstdtypecode>
    <startendstdtypenm>
     도착기준통행시간
    </startendstdtypenm>
    <startunitcode>
     101
    </startunitcode>
    <startunitnm>
     서울
    </startunitnm>
    <stddate>
     20220306
    </stddate>
    <stdtime>
     00:05
    </stdtime>
    <tcscartypecode>
     1
    </tcscartypecode>
    <tcscartypedivcode>
     1
    </tcscartypedivcode>
    <tcscartypedivname>
     소형차
    </tcscartypedivname>
    <tcscartypename>
     1종
    </tcscartypename>
    <timeavg>
     7.55
    </timeavg>
    <timemax>
     9.283
    </timemax>
    <timemin>
     6.566
    </timemin>
   </realunittrtmvo>
   <realunittrtmvo>
    <efcvtrfl>
     28
    </efcvtrfl>
    <endunitcode>
     103
    </endunitcode>
    <endunitnm>
     수원신갈
    </endunitnm>
    <startendstdtypecode>
     2
    </startendstdtypecode>
    <startendstdtypenm>
     도착기준통행시간
    </startendstdtypenm>
    <startunitcode>
     101
    </startunitcode>
    <startunitnm>
     서울
    </startunitnm>
    <stddate>
     20220306
    </stddate>
    <stdtime>
     00:10
    </stdtime>
    <tcscartypecode>
     1
    </tcscartypecode>
    <tcscartypedivcode>
     1
    </tcscartypedivcode>
    <tcscartypedivname>
     소형차
    </tcscartypedivname>
    <tcscartypename>
     1종
    </tcscartypename>
    <timeavg>
     7.55
    </timeavg>
    <timemax>
     11.350
    </timemax>
    <timemin>
     5.833
    </timemin>
   </realunittrtmvo>
   <realunittrtmvo>
    <efcvtrfl>
     81
    </efcvtrfl>
    <endunitcode>
     103
    </endunitcode>
    <endunitnm>
     수원신갈
    </endunitnm>
    <startendstdtypecode>
     2
    </startendstdtypecode>
    <startendstdtypenm>
     도착기준통행시간
    </startendstdtypenm>
    <startunitcode>
     101
    </startunitcode>
    <startunitnm>
     서울
    </startunitnm>
    <stddate>
     20220306
    </stddate>
    <stdtime>
     00:15
    </stdtime>
    <tcscartypecode>
     1
    </tcscartypecode>
    <tcscartypedivcode>
     1
    </tcscartypedivcode>
    <tcscartypedivname>
     소형차
    </tcscartypedivname>
    <tcscartypename>
     1종
    </tcscartypename>
    <timeavg>
     7.575
    </timeavg>
    <timemax>
     10.600
    </timemax>
    <timemin>
     5.766
    </timemin>
   </realunittrtmvo>
   <realunittrtmvo>
    <efcvtrfl>
     20
    </efcvtrfl>
    <endunitcode>
     103
    </endunitcode>
    <endunitnm>
     수원신갈
    </endunitnm>
    <startendstdtypecode>
     2
    </startendstdtypecode>
    <startendstdtypenm>
     도착기준통행시간
    </startendstdtypenm>
    <startunitcode>
     101
    </startunitcode>
    <startunitnm>
     서울
    </startunitnm>
    <stddate>
     20220306
    </stddate>
    <stdtime>
     00:20
    </stdtime>
    <tcscartypecode>
     1
    </tcscartypecode>
    <tcscartypedivcode>
     1
    </tcscartypedivcode>
    <tcscartypedivname>
     소형차
    </tcscartypedivname>
    <tcscartypename>
     1종
    </tcscartypename>
    <timeavg>
     7.566666666666666
    </timeavg>
    <timemax>
     10.600
    </timemax>
    <timemin>
     6.400
    </timemin>
   </realunittrtmvo>
   <realunittrtmvo>
    <efcvtrfl>
     446
    </efcvtrfl>
    <endunitcode>
     103
    </endunitcode>
    <endunitnm>
     수원신갈
    </endunitnm>
    <startendstdtypecode>
     2
    </startendstdtypecode>
    <startendstdtypenm>
     도착기준통행시간
    </startendstdtypenm>
    <startunitcode>
     101
    </startunitcode>
    <startunitnm>
     서울
    </startunitnm>
    <stddate>
     20220306
    </stddate>
    <stdtime>
     06
    </stdtime>
    <tcscartypecode>
     1
    </tcscartypecode>
    <tcscartypedivcode>
     1
    </tcscartypedivcode>
    <tcscartypedivname>
     소형차
    </tcscartypedivname>
    <tcscartypename>
     1종
    </tcscartypename>
    <timeavg>
     7.6
    </timeavg>
    <timemax>
     11.733
    </timemax>
    <timemin>
     5.950
    </timemin>
   </realunittrtmvo>
   <realunittrtmvo>
    <efcvtrfl>
     148
    </efcvtrfl>
    <endunitcode>
     103
    </endunitcode>
    <endunitnm>
     수원신갈
    </endunitnm>
    <startendstdtypecode>
     2
    </startendstdtypecode>
    <startendstdtypenm>
     도착기준통행시간
    </startendstdtypenm>
    <startunitcode>
     101
    </startunitcode>
    <startunitnm>
     서울
    </startunitnm>
    <stddate>
     20220306
    </stddate>
    <stdtime>
     06:00
    </stdtime>
    <tcscartypecode>
     1
    </tcscartypecode>
    <tcscartypedivcode>
     1
    </tcscartypedivcode>
    <tcscartypedivname>
     소형차
    </tcscartypedivname>
    <tcscartypename>
     1종
    </tcscartypename>
    <timeavg>
     7.533333333333333
    </timeavg>
    <timemax>
     9.433
    </timemax>
    <timemin>
     6.250
    </timemin>
   </realunittrtmvo>
   <realunittrtmvo>
    <efcvtrfl>
     39
    </efcvtrfl>
    <endunitcode>
     103
    </endunitcode>
    <endunitnm>
     수원신갈
    </endunitnm>
    <startendstdtypecode>
     2
    </startendstdtypecode>
    <startendstdtypenm>
     도착기준통행시간
    </startendstdtypenm>
    <startunitcode>
     101
    </startunitcode>
    <startunitnm>
     서울
    </startunitnm>
    <stddate>
     20220306
    </stddate>
    <stdtime>
     06:05
    </stdtime>
    <tcscartypecode>
     1
    </tcscartypecode>
    <tcscartypedivcode>
     1
    </tcscartypedivcode>
    <tcscartypedivname>
     소형차
    </tcscartypedivname>
    <tcscartypename>
     1종
    </tcscartypename>
    <timeavg>
     7.533333333333333
    </timeavg>
    <timemax>
     9.433
    </timemax>
    <timemin>
     6.250
    </timemin>
   </realunittrtmvo>
   <realunittrtmvo>
    <efcvtrfl>
     41
    </efcvtrfl>
    <endunitcode>
     103
    </endunitcode>
    <endunitnm>
     수원신갈
    </endunitnm>
    <startendstdtypecode>
     2
    </startendstdtypecode>
    <startendstdtypenm>
     도착기준통행시간
    </startendstdtypenm>
    <startunitcode>
     101
    </startunitcode>
    <startunitnm>
     서울
    </startunitnm>
    <stddate>
     20220306
    </stddate>
    <stdtime>
     06:10
    </stdtime>
    <tcscartypecode>
     1
    </tcscartypecode>
    <tcscartypedivcode>
     1
    </tcscartypedivcode>
    <tcscartypedivname>
     소형차
    </tcscartypedivname>
    <tcscartypename>
     1종
    </tcscartypename>
    <timeavg>
     7.566666666666666
    </timeavg>
    <timemax>
     9.433
    </timemax>
    <timemin>
     6.333
    </timemin>
   </realunittrtmvo>
  </data>
 </body>
</html>

In [8]:
timeAvg_lists = soup.find_all("timeavg")
stddate_lists = soup.find_all("stddate")
stdtime_lists = soup.find_all("stdtime")

In [9]:
timeAvg_lists

[<timeavg>7.516666666666667</timeavg>,
 <timeavg>7.5</timeavg>,
 <timeavg>7.55</timeavg>,
 <timeavg>7.55</timeavg>,
 <timeavg>7.575</timeavg>,
 <timeavg>7.566666666666666</timeavg>,
 <timeavg>7.6</timeavg>,
 <timeavg>7.533333333333333</timeavg>,
 <timeavg>7.533333333333333</timeavg>,
 <timeavg>7.566666666666666</timeavg>]

In [10]:
import lxml
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "http://data.ex.co.kr/openapi/trtm/realUnitTrtm?key=1308370912&type=xml&iStartUnitCode=101&iEndUnitCode=103"
result = requests.get(url)
content = result.content
soup = BeautifulSoup(content, "lxml") # html.parser 
# print(soup)
print(soup.prettify())

timeAvg_lists = soup.find_all("timeavg")
stddate_lists = soup.find_all("stddate")
stdtime_lists = soup.find_all("stdtime")

avgTime = []
stddate = []
stdtime = []
for timeAvg, date, time in zip(timeAvg_lists, stddate_lists, stdtime_lists):
  print(timeAvg, date, time)
  # print(time.get_text())
  avgTime.append(timeAvg.get_text())
  stddate.append(date.get_text())
  stdtime.append(time.get_text())

df = pd.DataFrame({
    "date": stddate, 
    "time": stdtime, 
    "avgTime": avgTime
})

df["student"] = "정승원"
df

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<html>
 <body>
  <data>
   <code>
    SUCCESS
   </code>
   <message>
    인증키가 유효합니다.
   </message>
   <count>
    1187
   </count>
   <numofrows>
    10
   </numofrows>
   <pageno>
    1
   </pageno>
   <pagesize>
    119
   </pagesize>
   <realunittrtmvo>
    <efcvtrfl>
     17
    </efcvtrfl>
    <endunitcode>
     103
    </endunitcode>
    <endunitnm>
     수원신갈
    </endunitnm>
    <startendstdtypecode>
     2
    </startendstdtypecode>
    <startendstdtypenm>
     도착기준통행시간
    </startendstdtypenm>
    <startunitcode>
     101
    </startunitcode>
    <startunitnm>
     서울
    </startunitnm>
    <stddate>
     20220306
    </stddate>
    <stdtime>
     00:25
    </stdtime>
    <tcscartypecode>
     1
    </tcscartypecode>
    <tcscartypedivcode>
     1
    </tcscartypedivcode>
    <tcscartypedivname>
     소형차
    </tcscartypedivname>
    <tcscartypename>
     1종
    </tcscartypename>
    <timeavg>
     7.533333333333333
    </timeavg>
    <timemax>
     9.066
    </timemax>
    <timemin>
     5.850
    </timemin>
   </realunittrtmvo>
   <realunittrtmvo>
    <efcvtrfl>
     57
    </efcvtrfl>
    <endunitcode>
     103
    </endunitcode>
    <endunitnm>
     수원신갈
    </endunitnm>
    <startendstdtypecode>
     2
    </startendstdtypecode>
    <startendstdtypenm>
     도착기준통행시간
    </startendstdtypenm>
    <startunitcode>
     101
    </startunitcode>
    <startunitnm>
     서울
    </startunitnm>
    <stddate>
     20220306
    </stddate>
    <stdtime>
     00:30
    </stdtime>
    <tcscartypecode>
     1
    </tcscartypecode>
    <tcscartypedivcode>
     1
    </tcscartypedivcode>
    <tcscartypedivname>
     소형차
    </tcscartypedivname>
    <tcscartypename>
     1종
    </tcscartypename>
    <timeavg>
     7.475
    </timeavg>
    <timemax>
     10.566
    </timemax>
    <timemin>
     5.750
    </timemin>
   </realunittrtmvo>
   <realunittrtmvo>
    <efcvtrfl>
     16
    </efcvtrfl>
    <endunitcode>
     103
    </endunitcode>
    <endunitnm>
     수원신갈
    </endunitnm>
    <startendstdtypecode>
     2
    </startendstdtypecode>
    <startendstdtypenm>
     도착기준통행시간
    </startendstdtypenm>
    <startunitcode>
     101
    </startunitcode>
    <startunitnm>
     서울
    </startunitnm>
    <stddate>
     20220306
    </stddate>
    <stdtime>
     00:35
    </stdtime>
    <tcscartypecode>
     1
    </tcscartypecode>
    <tcscartypedivcode>
     1
    </tcscartypedivcode>
    <tcscartypedivname>
     소형차
    </tcscartypedivname>
    <tcscartypename>
     1종
    </tcscartypename>
    <timeavg>
     7.466666666666667
    </timeavg>
    <timemax>
     10.566
    </timemax>
    <timemin>
     5.916
    </timemin>
   </realunittrtmvo>
   <realunittrtmvo>
    <efcvtrfl>
     15
    </efcvtrfl>
    <endunitcode>
     103
    </endunitcode>
    <endunitnm>
     수원신갈
    </endunitnm>
    <startendstdtypecode>
     2
    </startendstdtypecode>
    <startendstdtypenm>
     도착기준통행시간
    </startendstdtypenm>
    <startunitcode>
     101
    </startunitcode>
    <startunitnm>
     서울
    </startunitnm>
    <stddate>
     20220306
    </stddate>
    <stdtime>
     00:40
    </stdtime>
    <tcscartypecode>
     1
    </tcscartypecode>
    <tcscartypedivcode>
     1
    </tcscartypedivcode>
    <tcscartypedivname>
     소형차
    </tcscartypedivname>
    <tcscartypename>
     1종
    </tcscartypename>
    <timeavg>
     7.5
    </timeavg>
    <timemax>
     10.133
    </timemax>
    <timemin>
     5.966
    </timemin>
   </realunittrtmvo>
   <realunittrtmvo>
    <efcvtrfl>
     67
    </efcvtrfl>
    <endunitcode>
     103
    </endunitcode>
    <endunitnm>
     수원신갈
    </endunitnm>
    <startendstdtypecode>
     2
    </startendstdtypecode>
    <startendstdtypenm>
     도착기준통행시간
    </startendstdtypenm>
    <startunitcode>
     101
    </startunitcode>
    <startunitnm>
     서울
    </startunitnm>
    <stddate>
     20220306
    </stddate>
    <stdtime>
     00:45
    </stdtime>
    <tcscartypecode>
     1
    </tcscartypecode>
    <tcscartypedivcode>
     1
    </tcscartypedivcode>
    <tcscartypedivname>
     소형차
    </tcscartypedivname>
    <tcscartypename>
     1종
    </tcscartypename>
    <timeavg>
     7.566666666666666
    </timeavg>
    <timemax>
     9.750
    </timemax>
    <timemin>
     5.783
    </timemin>
   </realunittrtmvo>
   <realunittrtmvo>
    <efcvtrfl>
     14
    </efcvtrfl>
    <endunitcode>
     103
    </endunitcode>
    <endunitnm>
     수원신갈
    </endunitnm>
    <startendstdtypecode>
     2
    </startendstdtypecode>
    <startendstdtypenm>
     도착기준통행시간
    </startendstdtypenm>
    <startunitcode>
     101
    </startunitcode>
    <startunitnm>
     서울
    </startunitnm>
    <stddate>
     20220306
    </stddate>
    <stdtime>
     00:50
    </stdtime>
    <tcscartypecode>
     1
    </tcscartypecode>
    <tcscartypedivcode>
     1
    </tcscartypedivcode>
    <tcscartypedivname>
     소형차
    </tcscartypedivname>
    <tcscartypename>
     1종
    </tcscartypename>
    <timeavg>
     7.483333333333333
    </timeavg>
    <timemax>
     8.000
    </timemax>
    <timemin>
     5.966
    </timemin>
   </realunittrtmvo>
   <realunittrtmvo>
    <efcvtrfl>
     11
    </efcvtrfl>
    <endunitcode>
     103
    </endunitcode>
    <endunitnm>
     수원신갈
    </endunitnm>
    <startendstdtypecode>
     2
    </startendstdtypecode>
    <startendstdtypenm>
     도착기준통행시간
    </startendstdtypenm>
    <startunitcode>
     101
    </startunitcode>
    <startunitnm>
     서울
    </startunitnm>
    <stddate>
     20220306
    </stddate>
    <stdtime>
     00:55
    </stdtime>
    <tcscartypecode>
     1
    </tcscartypecode>
    <tcscartypedivcode>
     1
    </tcscartypedivcode>
    <tcscartypedivname>
     소형차
    </tcscartypedivname>
    <tcscartypename>
     1종
    </tcscartypename>
    <timeavg>
     7.383333333333334
    </timeavg>
    <timemax>
     8.500
    </timemax>
    <timemin>
     6.083
    </timemin>
   </realunittrtmvo>
   <realunittrtmvo>
    <efcvtrfl>
     99
    </efcvtrfl>
    <endunitcode>
     103
    </endunitcode>
    <endunitnm>
     수원신갈
    </endunitnm>
    <startendstdtypecode>
     2
    </startendstdtypecode>
    <startendstdtypenm>
     도착기준통행시간
    </startendstdtypenm>
    <startunitcode>
     101
    </startunitcode>
    <startunitnm>
     서울
    </startunitnm>
    <stddate>
     20220306
    </stddate>
    <stdtime>
     01
    </stdtime>
    <tcscartypecode>
     1
    </tcscartypecode>
    <tcscartypedivcode>
     1
    </tcscartypedivcode>
    <tcscartypedivname>
     소형차
    </tcscartypedivname>
    <tcscartypename>
     1종
    </tcscartypename>
    <timeavg>
     7.466666666666667
    </timeavg>
    <timemax>
     10.166
    </timemax>
    <timemin>
     5.800
    </timemin>
   </realunittrtmvo>
   <realunittrtmvo>
    <efcvtrfl>
     35
    </efcvtrfl>
    <endunitcode>
     103
    </endunitcode>
    <endunitnm>
     수원신갈
    </endunitnm>
    <startendstdtypecode>
     2
    </startendstdtypecode>
    <startendstdtypenm>
     도착기준통행시간
    </startendstdtypenm>
    <startunitcode>
     101
    </startunitcode>
    <startunitnm>
     서울
    </startunitnm>
    <stddate>
     20220306
    </stddate>
    <stdtime>
     01:00
    </stdtime>
    <tcscartypecode>
     1
    </tcscartypecode>
    <tcscartypedivcode>
     1
    </tcscartypedivcode>
    <tcscartypedivname>
     소형차
    </tcscartypedivname>
    <tcscartypename>
     1종
    </tcscartypename>
    <timeavg>
     7.416666666666667
    </timeavg>
    <timemax>
     9.666
    </timemax>
    <timemin>
     6.183
    </timemin>
   </realunittrtmvo>
   <realunittrtmvo>
    <efcvtrfl>
     8
    </efcvtrfl>
    <endunitcode>
     103
    </endunitcode>
    <endunitnm>
     수원신갈
    </endunitnm>
    <startendstdtypecode>
     2
    </startendstdtypecode>
    <startendstdtypenm>
     도착기준통행시간
    </startendstdtypenm>
    <startunitcode>
     101
    </startunitcode>
    <startunitnm>
     서울
    </startunitnm>
    <stddate>
     20220306
    </stddate>
    <stdtime>
     01:05
    </stdtime>
    <tcscartypecode>
     1
    </tcscartypecode>
    <tcscartypedivcode>
     1
    </tcscartypedivcode>
    <tcscartypedivname>
     소형차
    </tcscartypedivname>
    <tcscartypename>
     1종
    </tcscartypename>
    <timeavg>
     7.4
    </timeavg>
    <timemax>
     8.250
    </timemax>
    <timemin>
     6.833
    </timemin>
   </realunittrtmvo>
  </data>
 </body>
</html>
<timeavg>7.533333333333333</timeavg> <stddate>20220306</stddate> <stdtime>00:25</stdtime>
<timeavg>7.475</timeavg> <stddate>20220306</stddate> <stdtime>00:30</stdtime>
<timeavg>7.466666666666667</timeavg> <stddate>20220306</stddate> <stdtime>00:35</stdtime>
<timeavg>7.5</timeavg> <stddate>20220306</stddate> <stdtime>00:40</stdtime>
<timeavg>7.566666666666666</timeavg> <stddate>20220306</stddate> <stdtime>00:45</stdtime>
<timeavg>7.483333333333333</timeavg> <stddate>20220306</stddate> <stdtime>00:50</stdtime>
<timeavg>7.383333333333334</timeavg> <stddate>20220306</stddate> <stdtime>00:55</stdtime>
<timeavg>7.466666666666667</timeavg> <stddate>20220306</stddate> <stdtime>01  </stdtime>
<timeavg>7.416666666666667</timeavg> <stddate>20220306</stddate> <stdtime>01:00</stdtime>
<timeavg>7.4</timeavg> <stddate>20220306</stddate> <stdtime>01:05</stdtime>

       date   time            avgTime student
0  20220306  00:25  7.533333333333333     정승원
1  20220306  00:30              7.475     정승원
2  20220306  00:35  7.466666666666667     정승원
3  20220306  00:40                7.5     정승원
4  20220306  00:45  7.566666666666666     정승원
5  20220306  00:50  7.483333333333333     정승원
6  20220306  00:55  7.383333333333334     정승원
7  20220306   01    7.466666666666667     정승원
8  20220306  01:00  7.416666666666667     정승원
9  20220306  01:05                7.4     정승원

In [11]:
avgTime

['7.533333333333333',
 '7.475',
 '7.466666666666667',
 '7.5',
 '7.566666666666666',
 '7.483333333333333',
 '7.383333333333334',
 '7.466666666666667',
 '7.416666666666667',
 '7.4']

In [12]:
import pandas as pd

df = pd.DataFrame({
    "date": stddate, 
    "time": stdtime, 
    "avgTime": avgTime
})

df["student"] = "정승원"
df

       date   time            avgTime student
0  20220306  00:25  7.533333333333333     정승원
1  20220306  00:30              7.475     정승원
2  20220306  00:35  7.466666666666667     정승원
3  20220306  00:40                7.5     정승원
4  20220306  00:45  7.566666666666666     정승원
5  20220306  00:50  7.483333333333333     정승원
6  20220306  00:55  7.383333333333334     정승원
7  20220306   01    7.466666666666667     정승원
8  20220306  01:00  7.416666666666667     정승원
9  20220306  01:05                7.4     정승원