In [1]:
!pip install fake_useragent

Collecting fake_useragent
  Downloading fake-useragent-0.1.11.tar.gz (13 kB)
Building wheels for collected packages: fake-useragent
  Building wheel for fake-useragent (setup.py) ... done
  Created wheel for fake-useragent: filename=fake_useragent-0.1.11-py3-none-any.whl size=13502 sha256=ad1adefb7e1f4efcfa5dca0d131f3621e729f17db2c9803a74d99c4fc9ec3b66
  Stored in directory: /root/.cache/pip/wheels/ed/f7/62/50ab6c9a0b5567267ab76a9daa9d06315704209b2c5d032031
Successfully built fake-useragent
Installing collected packages: fake-useragent
Successfully installed fake-useragent-0.1.11

In [2]:
from bs4 import BeautifulSoup
import requests
from fake_useragent import UserAgent
from datetime import datetime
import time
import pandas as pd

def get_Code(company_code):
    url ="https://finance.naver.com/item/main.nhn?code=" + company_code
    ua = UserAgent()
    headers = { 'User-agent': ua.ie }
    response = requests.get(url, headers=headers)
    soup = BeautifulSoup(response.content, "html.parser")
    return soup
 
def get_Price(company_code):
    soup = get_Code(company_code)
    no_today = soup.select_one('p.no_today')
    print(no_today)
    blind = no_today.select_one('span.blind')
    return blind.text

def create_df(company_code, company_name, prices_list):
  data = pd.DataFrame({"종목코드": company_code, 
                       "상장회사": company_name, 
                       "주가": prices_list})
  return data
 
# 증시 기업코드
company_codes = ["030200", "005930", "068270", "035720"]
company_names = ["KT", "삼성전자", "셀트리온", "카카오"]

if __name__ == '__main__':
    now = datetime.now()
    print("-" * 60)
    print(now)
    print("-" * 60)
    
    prices_list = []
    for elm in company_codes:
        nowPrice = get_Price(elm)
        prices_list.append(nowPrice)

    # print(get_prices)

    stock_data = create_df(company_codes, company_names, prices_list)
    print(stock_data)

    print("-" * 60)

Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/browsers/0.1.11
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/fake_useragent/utils.py", line 154, in load
    for item in get_browsers(verify_ssl=verify_ssl):
  File "/usr/local/lib/python3.7/dist-packages/fake_useragent/utils.py", line 99, in get_browsers
    html = html.split('<table class="w3-table-all notranslate">')[1]
IndexError: list index out of range

------------------------------------------------------------
2022-04-21 07:21:56.775544
------------------------------------------------------------
<p class="no_today">
<em class="no_up">
<span class="blind">36,350</span>
<span class="no3">3</span><span class="no6">6</span><span class="shim">,</span><span class="no3">3</span><span class="no5">5</span><span class="no0">0</span>
</em>
</p>
<p class="no_today">
<em class="no_up">
<span class="blind">67,700</span>
<span class="no6">6</span><span class="no7">7</span><span class="shim">,</span><span class="no7">7</span><span class="no0">0</span><span class="no0">0</span>
</em>
</p>
<p class="no_today">
<em class="X">
<span class="blind">159,500</span>
<span class="no1">1</span><span class="no5">5</span><span class="no9">9</span><span class="shim">,</span><span class="no5">5</span><span class="no0">0</span><span class="no0">0</span>
</em>
</p>
<p class="no_today">
<em class="no_down">
<span class="blind">93,600</span>
<span class="no9">9</span><span class="no3">3</span><span class="shim">,</span><span class="no6">6</span><span class="no0">0</span><span class="no0">0</span>
</em>
</p>
     종목코드  상장회사       주가
0  030200    KT   36,350
1  005930  삼성전자   67,700
2  068270  셀트리온  159,500
3  035720   카카오   93,600
------------------------------------------------------------

In [3]:
import requests
import pandas as pd 
from bs4 import BeautifulSoup 

company_code = '005930' # 삼성전자
url ="https://finance.naver.com/item/sise_day.nhn?code=" + company_code
ua = UserAgent()
headers = { 'User-agent': ua.ie }
response = requests.get(url, headers=headers)
soup = BeautifulSoup(response.content, "html.parser")
# print(soup)

last_page = int(soup.select_one('td.pgRR').a['href'].split('=')[-1])
# print(last_page)

df = None 
count = 0
for page in range(1, last_page + 1):
  req = requests.get(f'{url}&page={page}', headers=headers)
  df = pd.concat([df, pd.read_html(req.text, encoding = "euc-kr")[0]], ignore_index=True)
  if count > 10:
    break
  count += 1

df.dropna(inplace=True)
df.reset_index(drop=True, inplace=True)

df.head()

           날짜       종가    전일비       시가       고가       저가         거래량
0  2022.04.21  67700.0  300.0  67600.0  68300.0  67500.0  12683245.0
1  2022.04.20  67400.0  100.0  67000.0  67400.0  66500.0  16693293.0
2  2022.04.19  67300.0  600.0  67100.0  68000.0  67000.0  12959434.0
3  2022.04.18  66700.0  100.0  66500.0  67100.0  66100.0  10119203.0
4  2022.04.15  66600.0  900.0  67200.0  67300.0  66500.0  13176415.0

In [4]:
last_page = int(soup.select_one('td.pgRR').a['href'].split('=')[-1])
print(last_page)

df = None 
count = 0
for page in range(1, last_page + 1):
  req = requests.get(f'{url}&page={page}', headers=headers)
  df = pd.concat([df, pd.read_html(req.text, encoding = "euc-kr")[0]], ignore_index=True)
  if count > 10:
    break
  count += 1

df.dropna(inplace=True)
df.reset_index(drop=True, inplace=True)

649

In [5]:
df

             날짜       종가     전일비       시가       고가       저가         거래량
0    2022.04.21  67700.0   300.0  67600.0  68300.0  67500.0  12683245.0
1    2022.04.20  67400.0   100.0  67000.0  67400.0  66500.0  16693293.0
2    2022.04.19  67300.0   600.0  67100.0  68000.0  67000.0  12959434.0
3    2022.04.18  66700.0   100.0  66500.0  67100.0  66100.0  10119203.0
4    2022.04.15  66600.0   900.0  67200.0  67300.0  66500.0  13176415.0
..          ...      ...     ...      ...      ...      ...         ...
115  2021.11.03  70400.0  1100.0  71700.0  71700.0  70100.0  12770428.0
116  2021.11.02  71500.0  1600.0  70800.0  72200.0  70700.0  16812570.0
117  2021.11.01  69900.0   100.0  70200.0  70600.0  69900.0  11503729.0
118  2021.10.29  69800.0   900.0  71200.0  71600.0  69700.0  17016151.0
119  2021.10.28  70700.0   600.0  69500.0  72200.0  69500.0  20644902.0

[120 rows x 7 columns]